layout_spectrum: 0.3914894
color:
  saturation: 0.7893617
  brandStrength: 1
  lightness: 0.8382978
  brandColors:
    - '#1E201F'
    - '#E1E9FA'
    - '#A37765'
    - '#AC2731'
    - '#B3BEBD'
  rhythmicContrast: 0.7226387
typography_spectrum: 0
name: CHENOCA Student Section
